services:
  ollama:
    image: ollama/ollama:0.12.11
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_KEEP_LIVE=4h
      
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.120.3
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST="${VM_IP_ADDRESS}"
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_LISTEN_ADDRESS="0.0.0.0"
      - GENERIC_TIMEZONE="Europe/London"
      - TZ="Europe/London"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SSL_KEY=/run/secrets/n8n_ssl_key
      - N8N_SSL_CERT=/run/secrets/n8n_ssl_cert
    secrets:
      - n8n_ssl_key
      - n8n_ssl_cert

volumes:
  ollama_data:
    name: "ollama-data"
  n8n_data:
    name: "n8n-data"

secrets:
  n8n_ssl_key:
    file: certs/n8n.key
  n8n_ssl_cert:
    file: certs/n8n.crt